### ISSUE TITLE
why "con.wait(lk, [&]{return synchronizeSensors();});  " last fo song long time.

### ISSUE THREAD

**Issue by jiejie567** [wh200720041/ssl_slam3#4]
I tested it, it lasted for about 40ms. Dose this part really need so much time?
And does your research group accept students from CSC exchange? I want to come and study, your work really impressed me.
Hope for your reply.

**Comment by jiejie567** [comment]
I have sloved the problem  now. Does your research group accept students from CSC exchange?

**Comment by wh200720041** [comment]
you can drop me an email wh200720041@gmail.com
